- name: Create a sandbox security group
  hosts: local
  connection: local
  become: False
  gather_facts: False
  vars_files:
    - vars.yaml

  tasks:
    - name: Create EC2 security group
      ec2_group:
        name: "{{ security_group }}"
        description: an example EC2 group
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access }}"
        aws_secret_key: "{{ aws_secret }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0



