- name: Create a sandbox bucket
  hosts: local
  connection: local
  become: False
  gather_facts: False
  vars:
    bucket_name: my-bucket
  vars_files:
    - vars.yaml

  tasks:
    - name: Creating a bucket with policies
      s3_bucket:
        name: "{{ bucket_name }}"
        policy: "{{ lookup('file','bucket_policy.json') }}"
        region: "{{ region }}"
        aws_access_key: "{{ aws_access }}"
        aws_secret_key: "{{ aws_secret }}"